DROP TABLE IF EXISTS tiles;

CREATE TABLE tiles(
    id BIGINT GENERATED ALWAYS AS UNIQUE PRIMARY KEY,
    material TEXT NOT NULL,
    shape TEXT NOT NULL,
    color TEXT NOT NULL,
    cost INTEGER NOT NULL
);