DROP TABLE IF EXISTS floors;
DROP TABLE IF EXISTS tiles;

CREATE TABLE floors (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    room TEXT NOT NULL,
    length INTEGER NOT NULL,
    width INTEGER NOT NULL
);

CREATE TABLE tiles (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    material TEXT NOT NULL,
    shape TEXT NOT NULL,
    color TEXT NOT NULL,
    cost INTEGER NOT NULL,
    floor_id BIGINT REFERENCES floors(id)
);